### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by Abdallah-Moh** [dar5hak/dar5hak#1]
Hi @dar5hak I saw from your bio that you know svelte I am working on an electron svelte app, it is a music player [Rhyme](https://github.com/Rhyme-Player/App) if you are not interested please tell me

**Comment by dar5hak** [comment]
Hey @Abdallah-Moh! Thanks for reaching out. I'm not an expert in Svelte and have not worked with Electron, but do let me know if you have a specific issue. I'll try my best to help out! :v:

**Comment by Abdallah-Moh** [comment]
do you have experience in ai with js

**Comment by dar5hak** [comment]
Nope

**Comment by Abdallah-Moh** [comment]
thanks for your response

**Comment by dar5hak** [comment]
No problem! Feel free to reach out any time.

**Comment by dar5hak** [comment]
I am enabling discussions and disabling issues on this repo. Feel free to use that.
